version: '3'
services:
  www:
    container_name: www
    build:
      args:
        TAG: $TAG
      dockerfile: ./Dockerfile
      context: .
    image: $TAG
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "3002:80"
