version: '3'
services:
  nginx:
    image: www.artem.fans:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "3002:80"
